/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author tasdi
 */
public class JavaTicTacToeFinal extends javax.swing.JFrame {

    private String startGame = "X";
    private int xCount = 0;
    private int oCount = 0;
    boolean checker;
    int turn = 0;
    boolean xFirst = true;
    private int tieChecker = 0;

    public JavaTicTacToeFinal() {
        initComponents();
        setSize(new java.awt.Dimension(950, 600));

    }

    private void gameScore() {

        jLblPlayerX.setText(String.valueOf(xCount));
        jLblPlayerO.setText(String.valueOf(oCount));
        tiecheck.setText(String.valueOf(tieChecker));

    }

    private void choosePlayer() {

        if (startGame.equalsIgnoreCase("X")) {

            startGame = "O";
        } else {
            startGame = "X";
        }
    }

    private void winningGame() {
        String b1 = jButton1.getText();
        String b2 = jButton2.getText();
        String b3 = jButton3.getText();
        String b4 = jButton4.getText();
        String b5 = jButton5.getText();
        String b6 = jButton6.getText();
        String b7 = jButton7.getText();
        String b8 = jButton8.getText();
        String b9 = jButton9.getText();

        // Rows
        if (b1.equals("X") && b2.equals("X") && b3.equals("X")
                || b4.equals("X") && b5.equals("X") && b6.equals("X")
                || b7.equals("X") && b8.equals("X") && b9.equals("X")) {
            JOptionPane.showMessageDialog(this, "Player X Wins", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
        } else if (b1.equals("O") && b2.equals("O") && b3.equals("O")
                || b4.equals("O") && b5.equals("O") && b6.equals("O")
                || b7.equals("O") && b8.equals("O") && b9.equals("O")) {
            JOptionPane.showMessageDialog(this, "Player O Wins", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
        } // Columns
        else if (b1.equals("X") && b4.equals("X") && b7.equals("X")
                || b2.equals("X") && b5.equals("X") && b8.equals("X")
                || b3.equals("X") && b6.equals("X") && b9.equals("X")) {
            JOptionPane.showMessageDialog(this, "Player X Wins", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
        } else if (b1.equals("O") && b4.equals("O") && b7.equals("O")
                || b2.equals("O") && b5.equals("O") && b8.equals("O")
                || b3.equals("O") && b6.equals("O") && b9.equals("O")) {
            JOptionPane.showMessageDialog(this, "Player O Wins", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
        } // Diagonals
        else if (b1.equals("X") && b5.equals("X") && b9.equals("X")
                || b3.equals("X") && b5.equals("X") && b7.equals("X")) {
            JOptionPane.showMessageDialog(this, "Player X Wins", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            xCount++;
            gameScore();
        } else if (b1.equals("O") && b5.equals("O") && b9.equals("O")
                || b3.equals("O") && b5.equals("O") && b7.equals("O")) {
            JOptionPane.showMessageDialog(this, "Player O Wins", "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            oCount++;
            gameScore();
        } else if (!b1.isEmpty()
                && !b2.isEmpty()
                && !b3.isEmpty()
                && !b4.isEmpty()
                && !b5.isEmpty()
                && !b6.isEmpty()
                && !b7.isEmpty()
                && !b8.isEmpty()
                && !b9.isEmpty()) {

           
            tieChecker++;
            gameScore();

            //all buttons must be filled for a tie
            JOptionPane.showMessageDialog(this, "TIC TAC TIE!!", "Good Game", JOptionPane.INFORMATION_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonNewGame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLblPlayerX = new javax.swing.JLabel();
        jLblPlayerO = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tiechecker = new javax.swing.JLabel();
        tiecheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton4.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 260, 150, 120);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 130, 150, 120);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton2.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 130, 150, 120);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton5.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 260, 150, 120);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton6.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton6.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(350, 260, 150, 120);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton7.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton7.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton7.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(30, 390, 150, 120);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton8.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton8.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton8.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(190, 390, 150, 120);

        jButtonExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonExit.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonExit.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit);
        jButtonExit.setBounds(750, 420, 120, 90);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton3.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 130, 150, 120);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 96)); // NOI18N
        jButton9.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton9.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton9.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(350, 390, 150, 120);

        jButtonNewGame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNewGame.setText("New Game");
        jButtonNewGame.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonNewGame.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonNewGame.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewGame);
        jButtonNewGame.setBounds(590, 320, 280, 90);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("PLAYER O:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 210, 120, 80);

        jButtonReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.setMaximumSize(new java.awt.Dimension(100, 100));
        jButtonReset.setMinimumSize(new java.awt.Dimension(100, 100));
        jButtonReset.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(590, 420, 120, 90);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tic Tac Toe");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 10, 260, 80);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("PLAYER X:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 120, 120, 80);

        jLblPlayerX.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLblPlayerX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPlayerX.setText("0");
        jLblPlayerX.setOpaque(true);
        jPanel1.add(jLblPlayerX);
        jLblPlayerX.setBounds(730, 130, 120, 80);

        jLblPlayerO.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLblPlayerO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPlayerO.setText("0");
        jLblPlayerO.setOpaque(true);
        jPanel1.add(jLblPlayerO);
        jLblPlayerO.setBounds(730, 220, 120, 80);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(530, 130, 10, 380);

        tiechecker.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        tiechecker.setText("Tie Checker:");
        jPanel1.add(tiechecker);
        tiechecker.setBounds(590, 80, 180, 33);

        tiecheck.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tiecheck.setText("0");
        tiecheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiecheckActionPerformed(evt);
            }
        });
        jPanel1.add(tiecheck);
        tiecheck.setBounds(740, 80, 90, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // set all buttons to X or O 
        jButton4.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton5.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButton8.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:

        // show confrim dialog
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Tic Tac Toe", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButton9.setText(startGame);

        if (startGame.equalsIgnoreCase("X")) {

            checker = false;
        } else {
            checker = true;
        }
        choosePlayer();
        winningGame();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed

        xFirst = !xFirst;

        if (xFirst == true) {
            turn = 0;
        } else {
            turn = 1;
        }

        //reset the game including player counts and initialize the count again so it becomes a new game
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton4.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton3.setEnabled(true);

        jLblPlayerX.setText("0");
        jLblPlayerO.setText("0");

        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
//        

    }//GEN-LAST:event_jButtonNewGameActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:

        //reset the game
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton4.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton3.setEnabled(true);

        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");


    }//GEN-LAST:event_jButtonResetActionPerformed

    private void tiecheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiecheckActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_tiecheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaTicTacToeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaTicTacToeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaTicTacToeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaTicTacToeFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new JavaTicTacToeFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblPlayerO;
    private javax.swing.JLabel jLblPlayerX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton tiecheck;
    private javax.swing.JLabel tiechecker;
    // End of variables declaration//GEN-END:variables
}